### ISSUE TITLE
Question - tests organization 

### ISSUE THREAD

**Issue by 0xorial** [rhys-vdw/ts-auto-guard#192] opened 2022-06-13 14:50 UTC
There are 2 things that feel a bit cumbersome when it comes to working with tests code:
- generate.ts file has grew quite large. perhaps it can be split?
- tape doesn't seem to be producing IDE(webstorm in my case)-friendly tests. how do you feel about switching to something more mainstream like mocha or jest?

**Comment by rhys-vdw** [comment] 2022-06-14 03:31
I like tap(e) personally, but I'm fine with changing it and reorganizing the tests if you think it'll make the project more maintainable and open to contribution. I'm not actively using this project, so my personal preferences shouldn't heavily influence that particular decision.

Looks like the issue is quite [a popular request for WebStorm](https://youtrack.jetbrains.com/issue/WEB-20916), but, as you say, not supported.

Go for it.

**Comment by rhys-vdw** [comment] 2022-10-17 13:23
Closed by #208

**Closed by rhys-vdw** 2022-10-17 13:23 UTC
