### ISSUE TITLE
template literals not processed correctly

### ISSUE THREAD

**Issue by juliandm** [rhys-vdw/ts-auto-guard#180] opened 2022-02-05 20:43 UTC
if you define types like this:
```typescript
export type HttpsString = "https://"
export type DomainEnding = "com" | "de"
export type UrlString = `${HttpsString}${string}.${DomainEnding}`

```

it turns into the following:
```typescript
...

export function isUrlString(obj: any, _argumentName?: string): obj is UrlString {
    return (
        (typeof obj === "`https://${string}.com`" ||
            typeof obj === "`https://${string}.de`")
    )
}

```

I was expecting it to generate a regex match expression instead of a typeof comparison

**Comment by rhys-vdw** [comment] 2022-02-05 23:54
Duplicate of #157. Pull requests welcome!

**Closed by rhys-vdw** 2022-02-05 23:54 UTC
